export const tableHeaders = [
    {
        name: 'First Name',
        key: 'firstName',
    },
    {
        name: 'Last Name',
        key: 'lastName',
    },
    {
        name: 'Phone Number',
        key: 'mobile',
    },
    {
        name: 'Email',
        key: 'email',
    },
    {
        name: 'Role',
        key: 'role',
      },
      {
        name: 'Created On',
        key: 'createdOn',
      },
      {
        name: 'Action',
        key: 'action',
    },
]

export const tableValues = [
    {
        firstName:'Leo',
        lastName:'John',
        mobile:'7401567040',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
    {
        firstName:'Mark',
        lastName:'Antony',
        mobile:'9443607857',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',

    },
    {
        firstName:'Christine',
        lastName:'Sweet',
        mobile:'8965412354',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
    {
        firstName:'Christine',
        lastName:'Sweet',
        mobile:'8965412354',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
    {
        firstName:'Christine',
        lastName:'Sweet',
        mobile:'8965412354',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
    {
        firstName:'Christine',
        lastName:'Sweet',
        mobile:'8965412354',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
    {
        firstName:'Christine',
        lastName:'Sweet',
        mobile:'8965412354',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
    {
        firstName:'Christine',
        lastName:'Sweet',
        mobile:'8965412354',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
    {
        firstName:'Christine',
        lastName:'Sweet',
        mobile:'8965412354',
        email:'test@test.com',
        role:'Admin',
        createdOn:'13-03-2022',
        action:'Action',
    },
        {
            firstName:'Christine',
            lastName:'Sweet',
            mobile:'8965412354',
            email:'test@test.com',
            role:'Admin',
            createdOn:'13-03-2022',
            action:'Action',
        },
]